const fs = require('fs');
const path = require('path');

const combinedSqlPath = path.join(__dirname, '../supabase/combined_upgrade.sql');
const cheatSheetPath = path.join(__dirname, '../SCHEMA_CHEATSHEET.md');

try {
  console.log('🚀 J.A.R.V.I.S. Schema Sync Engine Starting...');
  const sql = fs.readFileSync(combinedSqlPath, 'utf8');
  
  // Extract Tables
  const tableRegex = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([a-zA-Z0-9_.]+)\s*\(([\s\S]*?)\);/gi;
  let cheatSheet = `# 🧠 J.A.R.V.I.S. Database Schema Cheat Sheet\n\n`;
  cheatSheet += `> *This file is auto-generated by the Schema Sync Engine. Do not edit manually. AI Agents MUST read this file when writing Supabase queries to prevent hallucination.*\n\n`;
  cheatSheet += `## 🗄️ Tables & Columns\n\n`;
  
  let match;
  let tableCount = 0;
  while ((match = tableRegex.exec(sql)) !== null) {
    const tableName = match[1];
    const columns = match[2].split('\n')
      .map(line => line.trim())
      .filter(line => line && !line.startsWith('--') && !line.startsWith('CONSTRAINT') && !line.startsWith('PRIMARY KEY') && !line.startsWith('FOREIGN KEY') && !line.startsWith('UNIQUE'))
      .map(line => line.replace(/,$/, ''))
      .join('\n  ');
    
    cheatSheet += `### \`${tableName}\`\n\`\`\`sql\n  ${columns}\n\`\`\`\n\n`;
    tableCount++;
  }
  
  // Extract RPCs (Functions)
  const rpcRegex = /CREATE\s+OR\s+REPLACE\s+FUNCTION\s+([a-zA-Z0-9_.]+)\s*\(([\s\S]*?)\)\s*RETURNS/gi;
  cheatSheet += `## ⚡ Edge RPCs (Functions)\n\n`;
  let rpcCount = 0;
  while ((match = rpcRegex.exec(sql)) !== null) {
    const rpcName = match[1];
    const params = match[2].trim().replace(/\s+/g, ' ');
    cheatSheet += `- \`${rpcName}(${params})\`\n`;
    rpcCount++;
  }
  
  fs.writeFileSync(cheatSheetPath, cheatSheet);
  console.log(`✅ Schema Cheatsheet Generated successfully!`);
  console.log(`📊 Extracted ${tableCount} Tables and ${rpcCount} RPCs.`);
} catch (e) {
  console.error('❌ Failed to generate schema cheatsheet:', e);
}
